version: '3.8'

services:
  family-calendar:
    build: .
    container_name: family-calendar-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - DEBUG=false
      - DATABASE_URL=sqlite:///./data/family_calendar.db
      - HOST=0.0.0.0
      - PORT=8000
      - WORKERS=4
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - family-calendar-network

  nginx:
    image: nginx:alpine
    container_name: family-calendar-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-available:/etc/nginx/sites-available:ro
      - ./frontend:/var/www/frontend:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - family-calendar
    networks:
      - family-calendar-network

networks:
  family-calendar-network:
    driver: bridge

volumes:
  data:
  logs:
