"""Create kids and events tables

Revision ID: 713dd026e380
Revises: 1957b4fc706d
Create Date: 2025-09-04 11:16:34.936910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '713dd026e380'
down_revision = '1957b4fc706d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create kids table
    op.create_table('kids',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('color', sa.String(), nullable=False),
        sa.Column('avatar', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create events table
    op.create_table('events',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('location', sa.String(), nullable=True),
        sa.Column('start_utc', sa.DateTime(), nullable=False),
        sa.Column('end_utc', sa.DateTime(), nullable=False),
        sa.Column('rrule', sa.String(), nullable=True),
        sa.Column('exdates', sa.JSON(), nullable=True),
        sa.Column('kid_ids', sa.JSON(), nullable=True),
        sa.Column('category', sa.String(), nullable=False),
        sa.Column('source', sa.String(), nullable=False),
        sa.Column('created_by', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('kids')
    # ### end Alembic commands ###
