"""Create kids and events tables

Revision ID: 713dd026e380
Revises: 1957b4fc706d
Create Date: 2025-09-04 11:16:34.936910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '713dd026e380'
down_revision = '1957b4fc706d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
